apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-reconciler-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: namespace-reconciler-cluster-role
subjects:
  - kind: ServiceAccount
    name: ns-operator
    namespace: ns-operator